// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package api

import (
	"context"
	"github.com/sirupsen/logrus"
	"github.com/sotanext-team/medical-chain/src/sideservice/src/services"
)

// Injectors from api.wire.go:

func InitApiService(ctx context.Context, opts ApiServiceOptions) (*Service, error) {
	string2 := opts.Addr
	logger := opts.Logger
	indexApi := NewIndexApi(logger)
	cosmosService := opts.CosmosService
	cosmosApi := NewCosmosApi(logger, cosmosService)
	service := NewApiService(string2, indexApi, cosmosApi)
	return service, nil
}

// api.wire.go:

type ApiServiceOptions struct {
	Addr          string
	Logger        *logrus.Logger
	CosmosService *services.CosmosService
}
