apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: {{ .Values.service.name | quote }}
spec:
  ports:
  - name: http
    port: {{ .Values.services.port }}
  selector:
    app: "{{ .Values.service.name }}-selector"